//
// hbopencv2 - Binding library for Harbour++/Harbour/xHarbour and OpenCV2
//
// Copyright (c) 2025 Marcos Antonio Gambeta <marcosgambeta@outlook.com>
//

// macros for parameters
#define cv_par_IplImage(n) static_cast<IplImage *>(hb_parptr(n))
#define cv_cpar_IplImage(n) static_cast<const IplImage *>(hb_parptr(n))
#define cv_par_CvMat(n) static_cast<CvMat *>(hb_parptr(n))
#define cv_cpar_CvMat(n) static_cast<const CvMat *>(hb_parptr(n))
#define cv_par_CvArr(n) static_cast<CvArr *>(hb_parptr(n))
#define cv_cpar_CvArr(n) static_cast<const CvArr *>(hb_parptr(n))
#define cv_dpar_CvArr(n, def) HB_ISNIL(n) ? def : cv_par_CvArr(n)
#define cv_par_double(n) hb_parnd(n)
#define cv_dpar_double(n, def) HB_ISNIL(n) ? def : hb_parnd(n)
#define cv_par_float(n) static_cast<float>(hb_parnd(n))
#define cv_par_int(n) hb_parni(n)
#define cv_dpar_int(n, def) HB_ISNIL(n) ? def : hb_parni(n)
#define cv_par_size_t(n) hb_parnl(n)
#define cv_par_CvMatND(n) static_cast<CvMatND *>(hb_parptr(n))
#define cv_cpar_CvMatND(n) static_cast<const CvMatND *>(hb_parptr(n))
#define cv_par_CvSparseMat(n) static_cast<CvSparseMat *>(hb_parptr(n))
#define cv_cpar_CvSparseMat(n) static_cast<const CvSparseMat *>(hb_parptr(n))
#define cv_par_CvSparseMatIterator(n) static_cast<CvSparseMatIterator *>(hb_parptr(n))
//#define cv_cpar_CvSparseMatIterator(n) static_cast<const CvSparseMatIterator *>(hb_parptr(n))
#define cv_par_CvNArrayIterator(n) static_cast<CvNArrayIterator *>(hb_parptr(n))
//#define cv_cpar_CvNArrayIterator(n) static_cast<const CvNArrayIterator *>(hb_parptr(n))
#define cv_par_voidptr(n) static_cast<void *>(hb_parptr(n))
#define cv_cpar_voidptr(n) static_cast<const void *>(hb_parptr(n))
#define cv_dpar_voidptr(n, def) HB_ISNIL(n) ? def : static_cast<void *>(hb_parptr(n))
#define cv_par_CvSeq(n) static_cast<CvSeq *>(hb_parptr(n))
#define cv_cpar_CvSeq(n) static_cast<const CvSeq *>(hb_parptr(n))
#define cv_par_CvSet(n) static_cast<CvSet *>(hb_parptr(n))
#define cv_cpar_CvSet(n) static_cast<const CvSet *>(hb_parptr(n))
#define cv_par_CvSetElem(n) static_cast<CvSetElem *>(hb_parptr(n))
#define cv_cpar_CvMemStorage(n) static_cast<const CvMemStorage *>(hb_parptr(n))
#define cv_par_CvMemStorage(n) static_cast<CvMemStorage *>(hb_parptr(n))
#define cv_dpar_CvMemStorage(n, def) HB_ISNIL(n) ? def : static_cast<CvMemStorage *>(hb_parptr(n))
#define cv_par_CvMemStoragePos(n) static_cast<CvMemStoragePos *>(hb_parptr(n))
#define cv_par_CvSeqWriter(n) static_cast<CvSeqWriter *>(hb_parptr(n))
#define cv_cpar_CvFileNode(n) static_cast<const CvFileNode *>(hb_parptr(n))
#define cv_par_CvFileStorage(n) static_cast<CvFileStorage *>(hb_parptr(n))
#define cv_cpar_CvFileStorage(n) static_cast<const CvFileStorage *>(hb_parptr(n))
#define cv_par_CvSeqReader(n) static_cast<CvSeqReader *>(hb_parptr(n))
#define cv_par_CvFileNode(n) static_cast<CvFileNode *>(hb_parptr(n))
#define cv_cpar_CvModuleInfo(n) static_cast<const CvModuleInfo *>(hb_parptr(n))
#define cv_par_CvTreeNodeIterator(n) static_cast<CvTreeNodeIterator *>(hb_parptr(n))
#define cv_par_CvVideoWriter(n) static_cast<CvVideoWriter *>(hb_parptr(n))
#define cv_par_CvCapture(n) static_cast<CvCapture *>(hb_parptr(n))
#define cv_par_CvHistogram(n) static_cast<CvHistogram *>(hb_parptr(n))
#define cv_cpar_CvHistogram(n) static_cast<const CvHistogram *>(hb_parptr(n))
#define cv_par_IplConvKernel(n) static_cast<IplConvKernel *>(hb_parptr(n))
#define cv_cpar_CvTypeInfo(n) static_cast<const CvTypeInfo *>(hb_parptr(n))
#define cv_cpar_CvStringHashNode(n) static_cast<const CvStringHashNode *>(hb_parptr(n))
#define cv_par_CvLineIterator(n) static_cast<CvLineIterator *>(hb_parptr(n))
#define cv_cpar_CvGraph(n) static_cast<const CvGraph *>(hb_parptr(n))
#define cv_par_CvGraphScanner(n) static_cast<CvGraphScanner *>(hb_parptr(n))
#define cv_par_CvGraph(n) static_cast<CvGraph *>(hb_parptr(n))
#define cv_par_CvGraphVtx(n) static_cast<CvGraphVtx *>(hb_parptr(n))
#define cv_cpar_CvGraphVtx(n) static_cast<const CvGraphVtx *>(hb_parptr(n))
#define cv_cpar_CvGraphEdge(n) static_cast<const CvGraphEdge *>(hb_parptr(n))
#define cv_par_CvSeqBlock(n) static_cast<CvSeqBlock *>(hb_parptr(n))

// macros for return
#define cv_ret_IplImage(x) hb_retptr(x)
#define cv_ret_CvMat(x) hb_retptr(x)
#define cv_ret_CvArr(x) hb_retptr(x)
#define cv_ret_double(x) hb_retnd(x)
#define cv_ret_float(x) hb_retnd(x)
#define cv_ret_int(x) hb_retni(x)
#define cv_ret_voidptr(x) hb_retptr(x)
#define cv_ret_CvMatND(x) hb_retptr(x)
#define cv_ret_CvSeq(x) hb_retptr(x)
#define cv_ret_CvSparseMat(x) hb_retptr(x)
#define cv_ret_CvSparseNode(x) hb_retptr(x)
#define cv_ret_CvMemStorage(x) hb_retptr(x)
#define cv_ret_CvSet(x) hb_retptr(x)
#define cv_ret_CvSetElem(x) hb_retptr(x)
#define cv_ret_CvGraph(x) hb_retptr(x)
#define cv_ret_CvGraphEdge(x) hb_retptr(x)
#define cv_ret_CvGraphScanner(x) hb_retptr(x)
#define cv_ret_CvFileStorage(x) hb_retptr(x)
#define cv_ret_CvStringHashNode(x) hb_retptr(x)
#define cv_ret_CvTypeInfo(x) hb_retptr(x)
#define cv_ret_CvFileNode(x) hb_retptr(x)
#define cv_ret_CvVideoWriter(x) hb_retptr(x)
#define cv_ret_CvCapture(x) hb_retptr(x)
